### PR TITLE
Add Taproot Assets Protocol subserver

### PR DESCRIPTION
**Pull request by guggero**

### CODE REVIEW

**Review by ellemouton — APPROVED** [review]
LGTM 👍

**Comment by jamaljsr** [comment]
It looks like `tapcli` isn't created when you run `make go-install-cli` and also should be copied in the Docker image. It should be added to [Dockerfile](https://github.com/lightninglabs/lightning-terminal/blob/taproot-assets-subserver/Dockerfile) and [dev.Dockerfile](https://github.com/lightninglabs/lightning-terminal/blob/taproot-assets-subserver/dev.Dockerfile)

**Review by positiveblue — APPROVED** [review]
:+1:

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 🚀

**Review by ellemouton — APPROVED** [review]

**Pull request merged**
