### PR TITLE
mod: fix linter, bump Pool version, prepare for lnd 0.16, prepare for v0.9.0-alpha release

### PR DESCRIPTION
**Pull request by guggero**
We probably want to get https://github.com/lightninglabs/lightning-terminal/pull/516 in first, but I thought I'd prepare the master branch with the latest version of Pool in case anyone testing out `lnd v0.16.0-beta.rcX` runs into the MuSig2 upgrade error.
We'll only tag `v0.9.0-alpha` once the final version of lnd is out.

### CODE REVIEW

**Comment by levmi** [comment]
I believe that we'll also want to update the Loop client for release in `litd`. Working with the team to ensure we make that happen on the Loop side.

**Review by ellemouton — COMMENTED** [review]
Looks good but needs a `make protos` run :)

**Comment by guggero** [comment]
Bumped to final `lnd v0.16.0-beta`, `pool v0.22.0-beta` and `faraday 0.2.10-alpha`.

Ran into a weird linter issue that we had in a different project before and investigated for many hours... Disabled the linter for now.

**Comment by jamaljsr** [comment]
I'm getting this error when I run `make install`. I tried in both docker and natively on my machine. I'm using go v1.19 and confirmed I'm on commit https://github.com/lightninglabs/lightning-terminal/pull/518/commits/82b038dcf9dd5e3bbd2f5a02861b9d2139e26600

```
# github.com/lightninglabs/loop/loopdb
/Users/jamal/gocode/pkg/mod/github.com/lightninglabs/loop@v0.22.0-beta/loopdb/protocol_version.go:71:43: undefined: swapserverrpc.ProtocolVersion_MUSIG2
```

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 🚀

Just needs a `make protos` as there are Loop updates.

**Comment by guggero** [comment]
> I'm getting this error when I run `make install`. I tried in both docker and natively on my machine. I'm using go v1.19 and confirmed I'm on commit [82b038d](https://github.com/lightninglabs/lightning-terminal/commit/82b038dcf9dd5e3bbd2f5a02861b9d2139e26600)
> 
> ```
> # github.com/lightninglabs/loop/loopdb
> /Users/jamal/gocode/pkg/mod/github.com/lightninglabs/loop@v0.22.0-beta/loopdb/protocol_version.go:71:43: undefined: swapserverrpc.ProtocolVersion_MUSIG2
> ```

Oops, sorry, there was a tag missing in the Loop repo.

**Comment by guggero** [comment]
I pushed a docker image `guggero/lightning-terminal:v0.9.0-alpha` with the latest state of this PR (50228a8) if anyone wants to test with that.

**Review by ellemouton — APPROVED** [review]
tACK 🔥

**Pull request merged**
