### PR TITLE
Bump litd to version `v0.13.2-alpha`

### PR DESCRIPTION
**Pull request by ViktorTigerstrom**
This PR bumps the litd version to `v0.13.2-alpha`.

This PR also bumps lnd to version `v0.18.2-beta`.

### CODE REVIEW

**Review by guggero — APPROVED** [review]
utACK, LGTM :tada:

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 🚀

**Review by ellemouton — APPROVED** [review]
LGTM! 🎁

**Comment by ViktorTigerstrom** [comment]
Thanks for the reviews :tada:!

**Pull request merged**
