### PR TITLE
Bump `litd` to version `v0.13.5-alpha`

### PR DESCRIPTION
**Pull request by ViktorTigerstrom**
This PR bumps the litd version to `v0.13.5-alpha`.

This PR also bumps loop to `v0.28.8-beta`. Notably, the actual `loop` reference points to a branch based on top of
the `v0.28.8-beta` tag, which modifies `v0.28.8-beta` to use `lnd` version `v0.18.3-beta` rather than `v0.18.3-beta.rc1`.

### CODE REVIEW

**Comment by Lexie2520** [comment]
Well done

**Review by Lexie2520 — APPROVED** [review]

**Review by guggero — APPROVED** [review]
utACK, LGTM :tada:

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 🚀

Tested Loops via the litd UI and Terminal UI. Didn't run into any issues.

**Comment by ViktorTigerstrom** [comment]
Thanks a lot for the reviews @Lexie2520, @guggero & @jamaljsr :pray:!

**Pull request merged**
