### PR TITLE
ui+settings: update theme colors + border colors

### PR DESCRIPTION
**Pull request by dstrukt**
Apologies, should have probably done this in the last PR, but didn't fully know what it would entail, so didn't want to try to do everything in a single PR.

Just addresses `history` and `settings` to button up the basic things for the time being.

ui+settings: update theme colors + update border color on settings and history

Screenshots:
Screen Shot 2022-08-04 at 4 19 29 PM
Screen Shot 2022-08-04 at 4 19 32 PM
Screen Shot 2022-08-04 at 4 20 02 PM

### CODE REVIEW

**Review by jamaljsr — DISMISSED** [review]
tACK LGTM 👍 

Can you get the unit tests passing? Then we can merge this.

**Comment by dstrukt** [comment]
Nice, and will do, but I wasn't quite sure why the unit tests were failing here.

**Comment by jamaljsr** [comment]
You can click on the Details link next to the failing check below. The logs show the 2 failing tests. It looks like these tests are checking the colors of the DOM elements. You just need to update the values in the test to match the new colors.

When working locally on your machine, you can run `yarn test` to watch for changes and run tests every time you save a file. You can also run `yarn test:ci` which will run all tests. This is what the GitHub workflow is running.

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 👍

**Pull request merged**
