### PR TITLE
ui+connect: minor connect view styling updates

### PR DESCRIPTION
**Pull request by dstrukt**
The day has arrived, PRs for litd! 

Starting small though.

ui+common: adds `lightningRed` theme color
ui+connect: switches pink for new red color + updates bottom border color

Before:
Screen Shot 2022-08-03 at 7 50 30 PM

After:
Screen Shot 2022-08-03 at 7 48 53 PM

### CODE REVIEW

**Comment by dstrukt** [comment]
Trying to debug these errors.

**Review by jamaljsr — CHANGES_REQUESTED** [review]
tACK LGTM 👍 

Funny enough, I also updated the border color in the [home-screen](https://github.com/lightninglabs/lightning-terminal/pull/401/files#diff-1eb385475f2338560ea560c0f422988441c4529840580b179ca4cbcf4e5a72acR21) PR. It's fine to leave it here though, they will cancel each other out when merged.

To fix that error, you have to add the type definition for `lightningRed` to the `Theme` type in [emotion-theme.d.ts](https://github.com/lightninglabs/lightning-terminal/blob/master/app/src/emotion-theme.d.ts#L42).

**Comment by jamaljsr** [comment]
Can you rebase on master and squash these commits into one? There's no need for 3 commits to modify 4 lines of code. 😁

**Review by jamaljsr — APPROVED** [review]
LGTM. Thanks for the updates 🙌

**Pull request merged**
