### PR TITLE
mod+app: bump Pool version to v0.5.4-alpha, prepare for release 0.6.2

### PR DESCRIPTION
**Pull request by guggero**
With this commit we update the version of the Pool trader daemon to
v0.5.4-alpha. And we prepare the README for a new release of LiT
v0.6.2-alpha.

### CODE REVIEW

**Comment by jamaljsr** [comment]
I'm not sure if this is just an issue on my machine but when I try to create an order, I get a panic. I am running `litd` with all the daemons integrated including lnd.

```
$ pool orders submit bid --acct_key=023f94e65d95a40fa1c30c9b34232d47f2c1a292c342a7390577d5150a0c6efdd3 -amt=1000000 --interest_rate_percent=0.25 --lease_duration_blocks=2016 --min_chan_amt=100000 --max_batch_fee_rate=500 --force  --min_node_tier=0
```

```
zane_1          | panic: runtime error: invalid memory address or nil pointer dereference
zane_1          | [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xec3198]
zane_1          |
zane_1          | goroutine 9038 [running]:
zane_1          | github.com/lightninglabs/lndclient.AssertVersionCompatible(...)
zane_1          | 	/go/pkg/mod/github.com/lightninglabs/lndclient@v0.14.0-7/lnd_services.go:710
zane_1          | github.com/lightninglabs/pool.(*rpcServer).SubmitOrder.func1(0x4002508d88)
zane_1          | 	/go/pkg/mod/github.com/lightninglabs/pool@v0.5.4-alpha/rpcserver.go:1204 +0x18
zane_1          | github.com/lightninglabs/pool/order.ParseRPCOrder(0x7e000000005, 0x4002081b80, 0x4002d25680, 0x1, 0x1, 0xb627f8, 0x40009bf880, 0x24f9ee0)
zane_1          | 	/go/pkg/mod/github.com/lightninglabs/pool@v0.5.4-alpha/order/rpc_parse.go:102 +0x204
zane_1          | github.com/lightninglabs/pool.(*rpcServer).SubmitOrder(0x40023801e0, 0x24f9ee0, 0x4002654ed0, 0x4002a7f310, 0x0, 0x0, 0x0)
zane_1          | 	/go/pkg/mod/github.com/lightninglabs/pool@v0.5.4-alpha/rpcserver.go:1232 +0xbe4
zane_1          | github.com/lightninglabs/pool/poolrpc._Trader_SubmitOrder_Handler.func1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x0, 0x400078ccc0, 0x4002d25858, 0xc2519c)
zane_1          | 	/go/pkg/mod/github.com/lightninglabs/pool@v0.5.4-alpha/poolrpc/trader_grpc.pb.go:891 +0x7c
zane_1          | github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).middlewareUnaryServerInterceptor.func1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x4002e3c120, 0x4002476480, 0x400002c660, 0x40004a6310, 0x40002705a0, 0x4002266fa0)
zane_1          | 	/go/pkg/mod/github.com/lightningnetwork/lnd@v0.14.1-beta/rpcperms/interceptor.go:790 +0x24c
zane_1          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x1b, 0x0, 0x0, 0xc2533c)
zane_1          | 	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x58
zane_1          | github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).MacaroonUnaryServerInterceptor.func1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x4002e3c120, 0x4002e3c140, 0x45, 0x0, 0x0, 0x0)
zane_1          | 	/go/pkg/mod/github.com/lightningnetwork/lnd@v0.14.1-beta/rpcperms/interceptor.go:663 +0xa0
zane_1          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x0, 0x0, 0x40027ee998, 0xa2f1e0)
zane_1          | 	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x58
zane_1          | github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).rpcStateUnaryServerInterceptor.func1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x4002e3c120, 0x4002e3c160, 0x4002d25a48, 0x1e648, 0x4002e3c1a0, 0x20)
zane_1          | 	/go/pkg/mod/github.com/lightningnetwork/lnd@v0.14.1-beta/rpcperms/interceptor.go:754 +0x90
zane_1          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x119cc00, 0xffff6ef09840, 0xffff6e159c10, 0x20)
zane_1          | 	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x58
zane_1          | github.com/lightningnetwork/lnd/rpcperms.errorLogUnaryServerInterceptor.func1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x4002e3c120, 0x4002e3c180, 0x1224d20, 0x4002e3c1a0, 0xffff6eb100a8, 0x4002e3c120)
zane_1          | 	/go/pkg/mod/github.com/lightningnetwork/lnd@v0.14.1-beta/rpcperms/interceptor.go:579 +0x58
zane_1          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x0, 0x0, 0x40027eeb18, 0xe610a0)
zane_1          | 	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x58
zane_1          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x24f9ee0, 0x4002654ed0, 0x12729c0, 0x4002a7f310, 0x4002e3c120, 0x4002476480, 0x12768c0, 0x4002654ed0, 0x58, 0x12c8e40)
zane_1          | 	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbc
zane_1          | github.com/lightninglabs/pool/poolrpc._Trader_SubmitOrder_Handler(0x1379a80, 0x4000482000, 0x24f9ee0, 0x4002654ed0, 0x4002721980, 0x40004d09f0, 0x24f9ee0, 0x4002654ed0, 0x4002266fa0, 0x45)
zane_1          | 	/go/pkg/mod/github.com/lightninglabs/pool@v0.5.4-alpha/poolrpc/trader_grpc.pb.go:893 +0x12c
zane_1          | google.golang.org/grpc.(*Server).processUnaryRPC(0x400092f500, 0x250c7b8, 0x4000c70780, 0x40020b4b40, 0x40004d1350, 0x2fc6a28, 0x0, 0x0, 0x0)
zane_1          | 	/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292 +0x3fc
zane_1          | google.golang.org/grpc.(*Server).handleStream(0x400092f500, 0x250c7b8, 0x4000c70780, 0x40020b4b40, 0x0)
zane_1          | 	/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617 +0xa70
zane_1          | google.golang.org/grpc.(*Server).serveStreams.func1.2(0x4002761290, 0x400092f500, 0x250c7b8, 0x4000c70780, 0x40020b4b40)
zane_1          | 	/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940 +0x94
zane_1          | created by google.golang.org/grpc.(*Server).serveStreams.func1
zane_1          | 	/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:938 +0x1f8
```

**Comment by guggero** [comment]
Fixed the bug with the integrated Pool daemon. @ellemouton PTAL.

**Review by ellemouton — APPROVED** [review]
LGTM 🚀

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 👍

**Pull request merged**
