### PR TITLE
lightning-terminal: ensure reproducible releases

### PR DESCRIPTION
**Pull request by ViktorTigerstrom**
This is a copy of https://github.com/lightninglabs/lightning-terminal/pull/852 with no release docs, but based on the `0-19-staging` branch as @GeorgeTsagk requested that I'd open a PR for that branch as well :)

### CODE REVIEW

**Review by GeorgeTsagk — APPROVED** [review]
tACK
checksums are consistent across builds now :100:

**Comment by GeorgeTsagk** [comment]
rebased on top of `0-19-staging`

**Comment by GeorgeTsagk** [comment]
note: we get consistent checksums when building on the same host/machine, there is not yet consistency across multiple hosts

more on https://github.com/lightninglabs/lightning-terminal/issues/854

**Comment by guggero** [comment]
We don't want to add anything to the `0-19-staging` branch anymore. This should go into master (which will be done with https://github.com/lightninglabs/lightning-terminal/pull/852.

**Pull request closed without merging**
