### PR TITLE
Cleanup after upgrade to lnd v0.13.0-beta

### PR DESCRIPTION
**Pull request by guggero**
Replaces #238.

Fixes some small leftover issues after #226 was merged.

### CODE REVIEW

**Review by jamaljsr — APPROVED** [review]
LGTM 👍

**Review by Roasbeef — APPROVED** [review]
LGTM 🦭

**Comment by entone** [comment]
Any word on when this will make it to a Docker release?

**Comment by guggero** [comment]
We'll do a minor update (`v0.5.1-alpha`) soon, see #265.

**Comment by entone** [comment]
> We'll do a minor update (`v0.5.1-alpha`) soon, see #265.

Great, will this fix the macaroons not being created issue referenced in #241 ?

**Comment by guggero** [comment]
That should be fixed, yes.

**Pull request merged**
