### PR TITLE
multi: re-enable LNC handshake v2, bump dependencies for lnd 0.15.0-beta release

### PR DESCRIPTION
**Pull request by guggero**
This commit re-enables the second handshake for LNC.

### CODE REVIEW

**Review by ellemouton — DISMISSED** [review]
this looks familiar 🤓

**Comment by guggero** [comment]
cc @dstadulis (part of LiT update I mentioned).

**Review by ellemouton — COMMENTED** [review]
tACK! 🔥 
there just seems to be a panic in the itest that needs to be fixed.

**Review by ellemouton — DISMISSED** [review]
🔥

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 🥇 

Found one minor UI issue that I fixed in #382.

**Review by ellemouton — APPROVED** [review]

**Comment by kaloudis** [comment]
tACK

**Review by kaloudis — APPROVED** [review]

**Review by jamaljsr — APPROVED** [review]

**Pull request merged**
