### PR TITLE
Use go 1.16 embed instead of statik

### PR DESCRIPTION
**Pull request by guggero**
If we upgrade to go 1.16, we can simply use the `//go:embed` directive to compile everything in
the app/build directory into our root package.

### CODE REVIEW

**Review by jamaljsr — COMMENTED** [review]
Works as advertised on my testnet node. 👍 

The command `make go-install-cli` fails with the following error, so I cannot build my regtest docker node.

```
 Installing all CLI binaries.
GO111MODULE=on go install -v -trimpath -tags="litd autopilotrpc signrpc walletrpc chainrpc invoicesrpc watchtowerrpc" -ldflags " -X github.com/lightningnetwork/lnd/build.Commit=lightning-terminal-v0.4.1-alpha-2-gafbba3e0f323c6d8bf18d79521eb5deb605b1402 -X github.com/lightningnetwork/lnd/build.CommitHash=afbba3e0f323c6d8bf18d79521eb5deb605b1402 -X github.com/lightningnetwork/lnd/build.GoVersion= -X github.com/lightningnetwork/lnd/build.RawTags=litd,autopilotrpc,signrpc,walletrpc,chainrpc,invoicesrpc,watchtowerrpc -X github.com/lightninglabs/loop.Commit=v0.11.4-beta -X github.com/lightninglabs/pool.Commit=v0.4.4-alpha" github.com/lightningnetwork/lnd/cmd/lncli
/root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.12.1-beta/cmd/lncli/cmd_pay.go:18:2: missing go.sum entry for module providing package github.com/jedib0t/go-pretty/table (imported by github.com/lightningnetwork/lnd/cmd/lncli); to add:
	go get github.com/lightningnetwork/lnd/cmd/lncli@v0.12.1-beta
/root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.12.1-beta/cmd/lncli/cmd_pay.go:19:2: missing go.sum entry for module providing package github.com/jedib0t/go-pretty/text (imported by github.com/lightningnetwork/lnd/cmd/lncli); to add:
	go get github.com/lightningnetwork/lnd/cmd/lncli@v0.12.1-beta
/root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.12.1-beta/cmd/lncli/commands.go:21:2: missing go.sum entry for module providing package github.com/lightninglabs/protobuf-hex-display/json (imported by github.com/lightningnetwork/lnd/cmd/lncli); to add:
	go get github.com/lightningnetwork/lnd/cmd/lncli@v0.12.1-beta
/root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.12.1-beta/cmd/lncli/cmd_pay.go:20:2: missing go.sum entry for module providing package github.com/lightninglabs/protobuf-hex-display/jsonpb (imported by github.com/lightningnetwork/lnd/cmd/lncli); to add:
	go get github.com/lightningnetwork/lnd/cmd/lncli@v0.12.1-beta
/root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.12.1-beta/cmd/lncli/commands.go:23:2: missing go.sum entry for module providing package github.com/lightninglabs/protobuf-hex-display/proto (imported by github.com/lightningnetwork/lnd/cmd/lncli); to add:
	go get github.com/lightningnetwork/lnd/cmd/lncli@v0.12.1-beta
/root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.12.1-beta/cmd/lncli/autopilotrpc_active.go:9:2: missing go.sum entry for module providing package github.com/urfave/cli (imported by github.com/lightningnetwork/lnd/cmd/lncli); to add:
	go get github.com/lightningnetwork/lnd/cmd/lncli@v0.12.1-beta
Makefile:115: recipe for target 'go-install-cli' failed
make: *** [go-install-cli] Error 1
```

**Comment by guggero** [comment]
Thanks for checking that! There was something missing in the `go.mod` file, apparently `go v1.16` now cleans up too much if you use `go mod tidy`... Added a check for the CLI compilation.

**Review by jamaljsr — APPROVED** [review]
tACK 👍 

Works perfect now. Good idea to add the CI check.

**Review by Roasbeef — APPROVED** [review]
LGTM 💈

Very compact diff! Tested and works as expected for me. Also nice to shed an extra dependnacy along the way as well.

**Pull request merged**
