### PR TITLE
build: bump to lnd v0.15.5, bump version to v0.8.4

### PR DESCRIPTION
**Pull request by Roasbeef**

### CODE REVIEW

**Review by guggero — APPROVED** [review]

**Review by ellemouton — COMMENTED** [review]
I think we can just also include the latest Faraday changes in here. @guggero is busy pushing a tag for that

**Comment by guggero** [comment]
Yes, I pushed the tag `v0.2.9-alpha`.

**Comment by Roasbeef** [comment]
Updated to also bump to v0.29 for faraday.

**Review by ellemouton — APPROVED** [review]
LGTM! 🔥

**Pull request merged**
