### PR TITLE
version+README: update LiT and Loop versions

### PR DESCRIPTION
**Pull request by ellemouton**
This commit updates the integrated Loop version to v0.26.1-beta and
bumps Lit's version to v0.10.5-alpha

### CODE REVIEW

**Comment by bhandras** [comment]
I think we may also need to include https://github.com/lightninglabs/loop/pull/617 in this release.

**Comment by ellemouton** [comment]
> I think we may also need to include https://github.com/lightninglabs/loop/pull/617 in this release.

Ah - ok thanks. Will there be a loop release for this?

**Comment by ellemouton** [comment]
ok cool - I think this is ready now :)

**Comment by ellemouton** [comment]
oh dang - i was wrong 🙈

**Comment by guggero** [comment]
Ran into an issue with Loop when testing on my node, sorting out with the Loop team.

**Review by guggero — APPROVED** [review]
tACK, LGTM :tada:

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 🚀

**Pull request merged**
