### PR TITLE
firewall + firewalldb: fix typos

### PR DESCRIPTION
**Pull request by shuoer86**

### CODE REVIEW

**Review by ViktorTigerstrom — APPROVED** [review]
Thanks for the contribution @shuoer86! 🎉🚀

Nit:
If possible, you could also reword the commit title to:
`firewall + firewalldb: fix typos`

**Comment by shuoer86** [comment]
@ViktorTigerstrom Thanks for your review. I have reworded the commit title.

**Comment by ViktorTigerstrom** [comment]
> @ViktorTigerstrom Thanks for your review. I have reworded the commit title.

Thank you so much @shuoer86 🙏! Now we just need to await a second reviewer (which will be early next week), and this should be ready for merging, given that the second reviewer is satisfied as well :).

**Review by ellemouton — APPROVED** [review]
Thanks @shuoer86 !

**Pull request merged**
