### PR TITLE
multi: bump Loop to v0.20.0-beta, lnd min version to 0.15.0

### PR DESCRIPTION
**Pull request by guggero**
Fixes https://github.com/lightninglabs/lightning-terminal/issues/394.

Bumps the version of Loop to `v0.20.0-beta` and with that the minimum required version of a remote `lnd` node to `v0.15.0-beta`.

This will be released as `v0.7.1-alpha`.

### CODE REVIEW

**Review by levmi — DISMISSED** [review]
ACK. Chatted with Alex and we're good to move forward with `-experimental` flag being turned on by default in both `litd` and Terminal (on the web).

**Review by jamaljsr — COMMENTED** [review]
I'm not sure if we want to address this here or in the Loop repo or not at all. In my local regtest setup, I am still using bticoind v0.20. When performing a Loop Out, it never completes successfully. The swap status becomes stuck at `PREIMAGE_REVEALED`. I believe the looped out funds are now stuck in the on-chain HTLC and cannot be spent by the user.  Should we detect and inform the user of the incompatible bitcoind before starting the MuSig2 swap?

Relevant logs:
```
zane_1          | 2022-07-27 16:13:58.892 [INF] RPCS: Received new block notification: height=297
zane_1          | 2022-07-27 16:13:58.892 [INF] NTFN: Canceling confirmation notification: conf_id=15, script=1 aef0725198236bbd8678ec8e4802884fe31b3b81a22db3d00e4b9c4834bfaab4
zane_1          | 2022-07-27 16:13:58.892 [INF] NTFN: New spend subscription: spend_id=8, outpoint=d756367512deb136296173c719f0dd373e7bed9bcc359c3e6f67b80016a5dcab:0, script=1 0000000000000000000000000000000000000000000000000000000000000000, height_hint=296
zane_1          | 2022-07-27 16:13:58.892 [INF] NTFN: Dispatching historical spend rescan for outpoint=d756367512deb136296173c719f0dd373e7bed9bcc359c3e6f67b80016a5dcab:0, script=1 0000000000000000000000000000000000000000000000000000000000000000, start=296, end=297
zane_1          | 2022-07-27 16:13:58.897 [INF] SRVR: Adding preimage=9c33c7cd08e75038beb8eace72386fd670b018ec7b3355802806236acb8aff23 to witness cache
zane_1          | 2022-07-27 16:13:58.907 [INF] LOOP: 99110e Payment aab074459b2e46751e009f196f8c7e7f583b02a1900fb80b78f42281f74432a0: state=SUCCEEDED
zane_1          | 2022-07-27 16:14:08.896 [INF] LOOP: 99110e Loop out swap state: PreimageRevealed
zane_1          | 2022-07-27 16:14:08.896 [INF] LOOP: 99110e Pushing preimage to server
zane_1          | 2022-07-27 16:14:08.917 [INF] LOOP: 99110e Server update: SERVER_SUCCESS received, timestamp: 2022-07-27 16:14:08.913128254 +0000 UTC
zane_1          | 2022-07-27 16:14:08.917 [INF] LOOP: 99110e swap subscription: server finished serving updates
zane_1          | 2022-07-27 16:14:08.925 [INF] SRVR: Adding preimage=18d38bfea5225ba1ef3c42a55ecff645841ce8de6ed908eee63e5f938090bb65 to witness cache
zane_1          | 2022-07-27 16:14:08.930 [INF] LOOP: 99110e Payment 99110ecadb85ca32c67f90e3b5b28028e417180160db430a02da286b02f19815: state=SUCCEEDED
zane_1          | 2022-07-27 16:14:08.953 [INF] LOOP: 99110e Sweep on chain HTLC using MuSig2 to address bcrt1qhhjnu24wj76qqjkwf4n4athvl3jw7874n8ng2n fee 0.0000495 BTC (tx 6020ffa5e53822452f64945974adc975cce322917dc7cf75f9f43c68d5b841ba)
zane_1          | 2022-07-27 16:14:08.954 [INF] LNWL: Inserting unconfirmed transaction 6020ffa5e53822452f64945974adc975cce322917dc7cf75f9f43c68d5b841ba
zane_1          | 2022-07-27 16:14:08.968 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0x40025cce80)({
zane_1          |  Version: (int32) 2,
zane_1          |  TxIn: ([]*wire.TxIn) (len=1 cap=1) {
zane_1          |   (*wire.TxIn)(0x4002ace180)({
zane_1          |    PreviousOutPoint: (wire.OutPoint) d756367512deb136296173c719f0dd373e7bed9bcc359c3e6f67b80016a5dcab:0,
zane_1          |    SignatureScript: ([]uint8) {
zane_1          |    },
zane_1          |    Witness: (wire.TxWitness) (len=1 cap=1) {
zane_1          |     ([]uint8) (len=64 cap=64) {
zane_1          |      00000000  68 b6 0d cf 81 9d 8a 48  bb 9a ad 05 4f 56 85 bc  |h......H....OV..|
zane_1          |      00000010  45 7b ea 90 3e 04 ac b2  70 aa f1 c9 f1 b5 1c 57  |E{..>...p......W|
zane_1          |      00000020  bf 3d 80 53 7a 9c e6 3b  9c ec f7 b8 2e 4c cc 18  |.=.Sz..;.....L..|
zane_1          |      00000030  e4 e2 ab 2d b4 4a c5 5e  eb c4 f1 5f 32 a7 0f 4f  |...-.J.^..._2..O|
zane_1          |     }
zane_1          |    },
zane_1          |    Sequence: (uint32) 0
zane_1          |   })
zane_1          |  },
zane_1          |  TxOut: ([]*wire.TxOut) (len=1 cap=1) {
zane_1          |   (*wire.TxOut)(0x4002eef160)({
zane_1          |    Value: (int64) 495050,
zane_1          |    PkScript: ([]uint8) (len=22 cap=22) {
zane_1          |     00000000  00 14 bd e5 3e 2a ae 97  b4 00 4a ce 4d 67 5e ae  |....>*....J.Mg^.|
zane_1          |     00000010  ec fc 64 ef 1f d5                                 |..d...|
zane_1          |    }
zane_1          |   })
zane_1          |  },
zane_1          |  LockTime: (uint32) 297
zane_1          | })
zane_1          |
zane_1          | 2022-07-27 16:14:08.968 [ERR] RPCS: [/walletrpc.WalletKit/PublishTransaction]: unmatched backend error: -26: non-mandatory-script-verify-flag (Witness version reserved for soft-fork upgrades)
zane_1          | 2022-07-27 16:14:08.969 [WRN] LOOP: 99110e Publish of MuSig2 sweep failed: rpc error: code = Unknown desc = unmatched backend error: -26: non-mandatory-script-verify-flag (Witness version reserved for soft-fork upgrades)

*** mine 100+ blocks ***

zane_1          | 2022-07-27 16:21:04.763 [INF] NTFN: New block: height=408, sha=48e330b2cc59ff4238fdaffd71c0d452beafde1f0dcfabc2bb16a5ef9dc5e712
zane_1          | 2022-07-27 16:21:04.763 [INF] UTXN: Attempting to graduate height=408: num_kids=0, num_babies=0
zane_1          | 2022-07-27 16:21:04.764 [INF] RPCS: Received new block notification: height=408
zane_1          | 2022-07-27 16:21:14.814 [WRN] LOOP: 99110e Failed to create MuSig2 sweep txn: rpc error: code = Unknown desc = invalid sweep
zane_1          | 2022-07-27 16:21:48.245 [INF] CRTR: Pruning channel graph using block 7e4f937086adb0b8012d726c3ef658d8286f0a319142632405afb6089e313ea2 (height=409)
zane_1          | 2022-07-27 16:21:48.250 [INF] CRTR: Block 7e4f937086adb0b8012d726c3ef658d8286f0a319142632405afb6089e313ea2 (height=409) closed 0 channels
zane_1          | 2022-07-27 16:21:48.268 [INF] NTFN: New block: height=409, sha=7e4f937086adb0b8012d726c3ef658d8286f0a319142632405afb6089e313ea2
zane_1          | 2022-07-27 16:21:48.268 [INF] UTXN: Attempting to graduate height=409: num_kids=0, num_babies=0
zane_1          | 2022-07-27 16:21:48.268 [INF] RPCS: Received new block notification: height=409
zane_1          | 2022-07-27 16:21:58.321 [WRN] LOOP: 99110e Failed to create MuSig2 sweep txn: rpc error: code = Unknown desc = invalid sweep
```

**Comment by jamaljsr** [comment]
Also, can we update the protos to match the new Loop version here?

**Comment by bhandras** [comment]
Shouldn't `bitcoind` version be enforced on the LND side? @guggero 

Do you still have the nautilus logs? The "invalid sweep" error comes from the server side, might give us more insight of what went wrong.

**Comment by guggero** [comment]
> Shouldn't `bitcoind` version be enforced on the LND side? @guggero

Hmm, no, we didn't actually add that with Taproot. Might be something to think about in lnd 0.15.1? There might be a field to detect the version from indirectly.

**Comment by jamaljsr** [comment]
> Do you still have the nautilus logs? The "invalid sweep" error comes from the server side, might give us more insight of what went wrong.

Here are the full litd and nautilus logs.
[litd.log](https://github.com/lightninglabs/lightning-terminal/files/9201183/litd.log)
[nautilus.log](https://github.com/lightninglabs/lightning-terminal/files/9201184/nautilus.log)

**Comment by bhandras** [comment]
> > Do you still have the nautilus logs? The "invalid sweep" error comes from the server side, might give us more insight of what went wrong.
> 
> Here are the full litd and nautilus logs. [litd.log](https://github.com/lightninglabs/lightning-terminal/files/9201183/litd.log) [nautilus.log](https://github.com/lightninglabs/lightning-terminal/files/9201184/nautilus.log)

Okay what happened here is that the 100 blocks were quickly mined but the client only tried to sweep twice after that. I think if we were to mine 9 more blocks, the client would have tried to sweep on the script path, however would have failed in perpetuity from there since again bitcoind would not consume that transaction.

**Review by jamaljsr — APPROVED** [review]
tACK 👍  on bitcoind v0.21 and v22

**Comment by levmi** [comment]
Current plan of record: The path forward here is update `lnd` to have this flag that catches the `bitcoind` version and ensures that musig2 loop outs are only attempted with the compatible backend? once that's done in `lnd 0.15.1` then we'd cut a new loop client and then cut a new `litd`?

**Comment by guggero** [comment]
Will be replaced by https://github.com/lightninglabs/lightning-terminal/pull/418.

**Pull request closed without merging**
