### PR TITLE
mod+itest: bump loop and lnd dependencies

### PR DESCRIPTION
**Pull request by guggero**
With this commit we bump Loop to v0.18.0-beta and lnd to v0.14.3-beta.

Depends on the final release of `lnd v0.14.3-beta`.

### CODE REVIEW

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 🥇

**Comment by guggero** [comment]
With the final release of `lnd v0.14.3-beta`, `loop v0.18.0-beta`, `pool v0.5.6-alpha` and finally `lnc v0.1.9-beta` this PR is now ready to be tested and merged.

**Review by jamaljsr — APPROVED** [review]
tACK 🥇 

No issues running locally on regtest. Also tested connecting from the LNC v0.1.9 `example-server`. LGTM

**Review by jamaljsr — APPROVED** [review]
tACK https://github.com/lightninglabs/lightning-terminal/pull/348/commits/30d13ff7bb4e6ed4f4fdc44a12a9c2c9304b80df 👍 

Thanks for holding off on the LNC update.

**Review by kaloudis — APPROVED** [review]

**Pull request merged**
