### PR TITLE
Fix broken docker build by removing extra bash. Closes #137

### LINKED ISSUE #137: Dockerfile fails to build
docker build -f Dockerfile stops at a bash terminal after installing Yarn.
Exiting the terminal continues the build.

```
> Downloading tarball...

[1/2]: https://yarnpkg.com/latest.tar.gz --> /tmp/yarn.tar.gz.XXXXFOoeGe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0     78      0 --:--:-- --:--:-- --:--:--    78
100    93  100    93    0     0     52      0  0:00:01  0:00:01 --:--:--   134
100   643  100   643    0     0    236      0  0:00:02  0:00:02 --:--:--   870
100 1215k  100 1215k    0     0   204k      0  0:00:05  0:00:05 --:--:--  409k

[2/2]: https://yarnpkg.com/latest.tar.gz.asc --> /tmp/yarn.tar.gz.XXXXFOoeGe.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    61  100    61    0     0    340      0 --:--:-- --:--:-- --:--:--   338
100    97  100    97    0     0    186      0 --:--:-- --:--:-- --:--:--   186
100   647  100   647    0     0    725      0 --:--:-- --:--:-- --:--:--   725
100   832  100   832    0     0    703      0  0:00:01  0:00:01 --:--:--  812k
> WARNING: GPG is not installed, integrity can not be verified!
> Extracting to ~/.yarn...
> Adding to $PATH...
> We've added the following to your /root/.bashrc
> If this isn't the profile of your current shell then please add the following to your correct profile:

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

> Successfully installed Yarn 1.22.5! Please open another terminal where the `yarn` command will now be available.
bash-5.0#
```

### PR DESCRIPTION
**Pull request by stefanlsd**

### CODE REVIEW

**Review by guggero — APPROVED** [review]
Thanks for the fix, tACK!

Though I'm still not sure why it didn't work for you before this change (no problem on my machine and on @jamaljsr's, we used this file often enough), the extra bash invocation isn't needed because we explicitly execute the `.bashrc` file afterwards anyway.

**Comment by stefanlsd** [comment]
Thanks. Interesting. Locally i'm using podman but tested also with docker.io build infra and got an error (maybe unrelated).

podman version 2.1.1

**Comment by guggero** [comment]
Ah, I guess the defaults for interactivity with the host's terminal are probably different between `docker` and `podman`. Then this change should make the Dockerfile more portable which is great.

**Review by jamaljsr — APPROVED** [review]
tACK 👍 

The docker build still works on my machine with the `bash` line omitted.

**Pull request merged**
