### PR TITLE
multi: bump lnd version to v0.15.3-beta

### PR DESCRIPTION
**Pull request by guggero**
Package `lnd v0.15.3-beta` with LiT in integrated mode.

### CODE REVIEW

**Comment by guggero** [comment]
Sorry, requested feedback too early. We require a change in Loop because of a recent change to `invoicesrpc.SelectHopHints`.

**Comment by guggero** [comment]
Issue with the Loop client is now fixed, the PR is ready for review/testing.

**Review by ellemouton — APPROVED** [review]
LGTM! 🔥  Thanks for opening this - I wont forget in future 😅

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 👍

Sorry for the delayed review. I needed to finish up on some other work before switching to this branch and losing my node state.

**Pull request merged**
